export enum Role {
  OWNER = 'OWNER',
  GUARDIAN = 'GUARDIAN',
  MEMBER = 'MEMBER',
  PRIVATE_MODE = 'PRIVATE_MODE',
  DOCTOR = 'DOCTOR',
  PHARMACY = 'PHARMACY',
  INSURANCE = 'INSURANCE',
  SUPER_ADMIN = 'SUPER_ADMIN'
}
